enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

nmHoistingLimits: workspaces

nmSelfReferences: true

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.38.cjs

logFilters:
  - code: YN0002
    level: discard
  - code: YN0061
    level: discard
  - code: YN0032
    level: discard
