name: Lint
on:
  push:
    paths:
      - src/**
      - .github/workflows/lint.yml
      - .eslintignore
      - .eslintrc
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_ES: true
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc
          DEFAULT_BRANCH: latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
