name: Lint
on:
  push:
    paths:
      - src/**
      - .github/workflows/lint.yml
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4.9.4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
